# Default values for kuzzle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: kuzzleio/kuzzle
  tag: 2
  pullPolicy: Always

imagePullSecrets: []

labels: {}
podLabels: {}

nameOverride: ""
fullnameOverride: ""

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

podSecurityContext:
  fsGroup: 1000

extraEnvs:
  - name: kuzzle_services__storageEngine__client__node
    value: http://elasticsearch-master:9200
  - name: kuzzle_services__internalCache__node__host
    value: redis-master
  - name: kuzzle_services__memoryStorage__node__host
    value: redis-master
  - name: NODE_ENV
    value: production

command: ["kuzzle", "start"]
args: []

entrypoints:
  http:
    port: 7512
    targetPort: 7512
  cluster_command:
    port: 7510
    targetPort: 7510
  cluster_sync:
    port: 7511
    targetPort: 7511

extraEntrypoints:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP

  - name: debug
    port: 9229
    targetPort: 9229
    protocol: TCP

probes:
  liveness:
    httpGet:
      path: /_publicApi
      port: kuzzle-api
  readiness:
    httpGet:
      path: /_publicApi
      port: kuzzle-api

metrics:
  port: 7512
  path: "/_/prometheus/metrics"

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Extra Containers to run before the main container in the pod (e.g. for sidecar containers)
# extraContainers:
#   - name: my-sidecar
#     image: my-sidecar-image
#     imagePullPolicy: Always
#     resources:
#       {}
#     volumeMounts:
#       - name: my-volume
#         mountPath: /path/to/my-volume
extraInitContainers: []
