{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.host }}
  namespace: {{ .Values.certificate.namespace }}
spec:
  commonName: {{ .Values.certificate.host }}
  secretName: {{ .Values.certificate.name }}
  {{ with .Values.certificate.dnsNames }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
{{- end }}