{{- if .Values.ingressTCP.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Values.ingressTCP.name }}
  namespace: {{ .Values.ingressTCP.namespace }}
  {{- with .Values.ingressTCP.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingressTCP.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingressTCP.routes }}
  routes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingressTCP.tls.enabled }}
  tls:
    secretName: {{ .Values.ingressTCP.tls.secretName }}
  {{- end }}
{{- end }}
