{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
data:
  .dockerconfigjson: >-
    {{ .Values.secret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
