apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuzzle.fullname" . }}
  labels:
    {{- include "kuzzle.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.entrypoints.http.port }}
      targetPort: {{ .Values.entrypoints.http.targetPort }}
      protocol: TCP
      name: kuzzle-api
    - port: {{ .Values.entrypoints.cluster_command.port }}
      targetPort: {{ .Values.entrypoints.cluster_command.targetPort }}
      protocol: TCP
      name: cluster-command
    - port: {{ .Values.entrypoints.cluster_sync.port }}
      targetPort: {{ .Values.entrypoints.cluster_sync.targetPort }}
      protocol: TCP
      name: cluster-sync
  {{- with .Values.extraEntrypoints }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "kuzzle.selectorLabels" . | nindent 4 }}
