{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: webapp-docker
  namespace: {{ .Values.ingress.namespace }}
data:
  .dockerconfigjson: >-
    {{ .Values.secret.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
