{{- if .Values.secretRoute53.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRoute53.name }}
  namespace: {{ .Values.secretRoute53.namespace }}
data:
  secret-access-key: {{ .Values.secretRoute53.secret_key }}
type: Opaque
{{- end }}
