apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.core" . }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.chirpstack.http.port }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard

    {{- if .Values.chirpstack.metrics.enabled }}
    - port: {{ .Values.chirpstack.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{ end }}
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
    component: core
