ingress:
  enabled: false

ingressTCP:
  enabled: false

certificate:
  enabled: true

kuzzle:
  replicaCount: 1

  command: null

  image:
    name: kuzzleio/kuzzle
    tag: 2
    pullPolicy: Always

  imagePullSecrets:
    - name: "kuzzle-docker"

  extraEnvs:
    - name: kuzzle_services__storageEngine__client__node
      value: http://elasticsearch-master:9200
    - name: kuzzle_services__internalCache__node__host
      value: redis-master
    - name: kuzzle_services__memoryStorage__node__host
      value: redis-master
    - name: NODE_ENV
      value: production

  metrics:
    port: 7512
    path: "/_/metrics"

elasticsearch:
  replicas: 1
  imageTag: 7.10.2
  minimumMasterNodes: 1


  roles:
    master: "true"
    ingest: "true"
    data: "true"
    remote_cluster_client:
    ml:

  esJavaOpts: "-Xmx512m -Xms512m"

  resources:
    requests:
      cpu: "700m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1G"

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "scw-bssd"
    resources:
      requests:
        storage: "15Gi"

redis:
  usePassword: false
  master:
    persistence:
      enabled: true
      size: "10Gi"
  slave:
    persistence:
      enabled: true
      size: "10Gi"
  cluster:
    enabled: true
    slaveCount: 1
  metrics:
    enabled: true
  resources:
    requests:
      cpu: "300m"
      memory: "150Mi"
    limits:
      cpu: "600m"
      memory: "250Mi"