ingress:
  enabled: false

ingressTCP:
  enabled: false

certificate:
  enabled: false

kuzzle:
  replicaCount: 1

  image:
    name: kuzzleio/kuzzle
    tag: "2.47.0"
    pullPolicy: Always

  imagePullSecrets:
    - name: "kuzzle-docker"

  extraEnvs:
    - name: kuzzle_services__storageEngine__client__node
      value: http://elasticsearch-master:9200
    - name: kuzzle_services__internalCache__node__host
      value: redis-master
    - name: kuzzle_services__memoryStorage__node__host
      value: redis-master
    - name: NODE_ENV
      value: production
    - name: kuzzle_services__storageEngine__majorVersion
      value: "7"

  metrics:
    port: 7512
    path: "/_/metrics"

elasticsearch:
  replicas: 1
  imageTag: 7.10.2
  minimumMasterNodes: 1

  roles:
    master: "true"
    ingest: "true"
    data: "true"
    remote_cluster_client:
    ml:

  esJavaOpts: "-Xmx512m -Xms512m"

  resources:
    requests:
      cpu: "700m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "1G"

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "scw-bssd"
    resources:
      requests:
        storage: "15Gi"

redis:
  auth:
    enabled: false

  master:
    persistence:
      enabled: true
      size: "10Gi"

    resources:
      requests:
        cpu: "300m"
        memory: "150Mi"

      limits:
        cpu: "600m"
        memory: "250Mi"

  replica:
    replicaCount: 1

    persistence:
      enabled: true
      size: "10Gi"

    resources:
      requests:
        cpu: "300m"
        memory: "150Mi"

      limits:
        cpu: "600m"
        memory: "250Mi"

  metrics:
    enabled: true
