webapp:
  replicaCount: 1

  image:
    name: nginx
    tag: latest
    pullPolicy: Always

  imagePullSecrets:
    - name: "webapp-docker"

  updateStrategy: RollingUpdate

  service:
      port: 80
      targetPort: 80


secretRoute53:
  enabled: true
  name: route53-secret
  namespace: default
  secret_key: bXktc3VwZXItc2VjcmV0LWtleQ==


secret:
  enabled: true
  name: webapp-secret
  dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeSI6IHsKICAgICAgImF1dGgiOiAiWVdSdGFXNDZjR0Z6YzNkdmNtUT0iCiAgICB9CiAgfQp9

certificate:
  enabled: true

  issuer: letsencrypt
  host: webapp.test
  namespace: default
  name: webapp

  dnsNames:
    - webapp.test

ingress:
  enabled: true

  name: webapp
  namespace: default

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    certmanager.k8s.io/acme-challenge-type: dns01

  entrypoints:
    - websecure

  routes:
    - match: Host(`webapp.test`)
      kind: Rule
      services:
        - name: webapp
          port: 7512
          namespace: default
  tls:
    enabled: true
    secretName: webapp