webapp:
  replicaCount: 1

  image:
    name: nginx
    tag: latest
    pullPolicy: Always


  updateStrategy: RollingUpdate

  service:
      port: 80
      targetPort: 80

  # Configure extra entrypoints
  # extraEntrypoints:
  #   - name: mqtt
  #     port: 1883
  #     targetPort: 1883
  #     protocol: TCP

