apiVersion: v1
kind: Service
metadata:
  name: {{ include "qpack.fullname" . }}
  labels:
    {{- include "qpack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  {{- with .Values.extraEntrypoints }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "qpack.selectorLabels" . | nindent 4 }}

