apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iot.fullname" . }}
  labels:
    {{- include "iot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "iot.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      labels:
        {{- include "iot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            {{- toYaml .Values.extraEnvs | nindent 12 }} 
          command: 
            {{- toYaml .Values.command | nindent 12 }}
          args: 
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.probes.liveness.enable }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness.config | nindent 12 }} 
          {{- end }}
          {{- if .Values.probes.readiness.enable }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness.config | nindent 12 }} 
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

