{{- if .Values.chirpstackRestApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.restApi" . }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
  {{- with .Values.chirpstackRestApi.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.chirpstackRestApi.service.type }}
  {{- with .Values.chirpstackRestApi.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.chirpstackRestApi.http.port }}
      targetPort: {{ .Values.chirpstackRestApi.http.containerPort }}
      protocol: TCP
      name: api
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: restApi
{{- end }}
