name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3

      - name: Run repo update
        run: |
          helm repo add kuzzle https://kuzzleio.github.io/helm-charts/
          helm repo add elastic https://helm.elastic.co/
          helm repo add bitnami https://charts.bitnami.com/bitnami/
          helm repo add codecentric https://codecentric.github.io/helm-charts/
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
